### PR TITLE
Adding frontend gotchas

### PR DESCRIPTION
**Pull request by benbarnett**
I'll create a link to this document from the main frontend repo (along with some other reference material).

@nmiddleweek suggested putting this document together, which seems like a great idea for new starters and well, anyone writing frontend code at MAS.

Completely open to suggestions!

### CODE REVIEW

**Comment by johnplayer1982** [comment]
I like that a lot, very useful! thanks Ben :+1:

**Comment by munckymagik** [comment]
:+1: like v much

**Comment by mconnell** [comment]
:+1:

**Comment by nkmdk-007** [comment]
Nice!

**Pull request merged**
